# Generated by Django 5.2.7 on 2025-10-15 12:32

from django.db import migrations
from datetime import datetime
from django.utils import timezone


def fill_field_with_values(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_field_with_values)
    ]
