# Generated by Django 5.2.7 on 2025-10-17 10:53

from django.db import migrations
import phonenumbers

def parse_phonenumbers(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(parse_phonenumbers)
    ]
