# Generated by Django 5.2.7 on 2025-10-17 15:55

from django.db import migrations


def copy_owners(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    Owner = property.get_model('property', 'Owner')
    
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            owners_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        owner.owners_flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_owner_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_owners)
    ]