# Generated by Django 5.2.7 on 2025-10-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_complaint_flat_alter_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_flats',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
